library(countrycode)
library(dplyr)
library(readr)
library(nnet)
library(ggplot2)
library(zoo)
library(patchwork)
library(table1)
library(tibble)
library(gridExtra)
library(grid)
library(here)
library(tidyr)
library(htmlTable)
library(arsenal)


cli::cli_alert("- Cleaning Data")
source("Analysis/1. Data Cleaning.R")

cli::cli_alert_info(" - Creating functions")
source("Analysis/2. Country-level dataset.R")
source("Analysis/3. Pooled Models.R")
source("Analysis/4. Country-level models - Sensitivity Analysis.R")
source("Analysis/4.5 Romania models - Sensitivity Analysis.R")
source("Analysis/5. Model Plots.R")
source("Analysis/6. Time Series Plot.R")

cli::cli_alert_info(" - Getting Results")
source("Analysis/Summary Tables.R")
source("Analysis/Pooled Results.R")
source("Analysis/CountryLevelResults.R")
source("Analysis/TimeSeries.R")
source("Analysis/Correlation Heatmaps - Confidence.R")

